Controllers spec
Fsher07/blog-app-rails pull request #5
Opened 2022-07-21 09:44 UTC by Fsher07

- Add RSpec as a gem to your project.
- Create a Request spec file for all your controllers.
- Make sure that for each action you check:
    - If response status was correct.
    - If a correct template was rendered.
    - If the response body includes correct placeholder text.

2022-07-21 11:21 UTC, codepantha requested changes
# STATUS: REQUIRED CHANGES ♻️ 

## Hi @Fsher07 👋, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

### Highlights ⭐ 
✔️ Descriptive PR
✔️ Correct GitFlow
✔️ No linter errors
✔️ Professional README

## Required Changes ♻️
_Check the comments under the review._

- [ ] Your migrations are not running correctly so I'm unable to adequately review your project. Please take a look at the error below and fix it 🙏 
![image](https://user-images.githubusercontent.com/46839548/180201033-39358e74-fc2f-4c7a-9165-2768c60def98.png)


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-21 13:32 UTC, Fsher07 commented
Hi @codepantha, thank you for your review.  I replicated the same step but it works for me. That's why I do not know what to do.
![image](https://user-images.githubusercontent.com/96717968/180225325-ab9eb43e-6fd7-4e66-8b84-c1b32646acdf.png)

2022-07-21 13:54 UTC, codepantha commented
@Fsher07 👋 I took some time to look at it and your migrations seem to be in order so it's a bit strange that it's not working 🤔. Please request another review.

2022-07-22 11:25 UTC, ahmetbozaci requested changes
# ♻️♻️♻️ STATUS: Changes Required  ♻️♻️♻️ 
![](https://media.giphy.com/media/3pZipqyo1sqHDfJGtz/giphy.gif)
@Fsher07  ✋🏼 
#### Great work on making the changes requested by a previous reviewer 👏 
#### You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.
___ 

### 💯  Highlights 💯
- Your git-flow is correct. ✔️
- You set up linter files and no errors. ✔️
- Your pull request is very professional. It has a meaningful title and summary. Keep it up.✔️
___

### ♻️ Request changes ♻️

- [ ] _Check the comments under the review._

___

### Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
___

### Cheers and Happy coding! 💻 👏
![almost](https://media.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif)


___

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification._

_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._
___

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form.](https://airtable.com/shrQAqnBwek5a0O0s)_

[GitHub](https://github.com/ahmetbozaci) | [LinkedIn](https://linkedin.com/in/ahmetbozaci) | [Twitter](https://twitter.com/ahmtbozaci)

_Reviewed by [Ahmet Bozacı ](https://github.com/ahmetbozaci)_

2022-07-22 11:25 UTC, ahmetbozaci commented on spec/requests/user_controller_spec.rb
> +end
- [ ] Kindly fix the error.

![image](https://user-images.githubusercontent.com/38635158/180428897-32c3975e-6e59-4af1-9c6c-842f9f7803de.png)

2022-07-22 13:26 UTC, Mre55 approved these changes
**Hi @Fsher07,**

# Status: APPROVED 🏆 🎉 🎊 

Your project is complete!  There is nothing else to say other than... it's time to merge it  🚀: 
Congratulations! 🎉 

## To highlight 🎯

- All test written well and pass ✅ 
- The PR title and description are professional and descriptive ✅ 
- The commit messages are meaningful ✅ 
- Linters are working properly ✅ 

<img src="https://media3.giphy.com/media/xT0xezQGU5xCDJuCPe/giphy.gif"/>


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-22 14:13 UTC, merged